### ISSUE TITLE
xcode 8.2, ip7plus模拟器崩溃

### ISSUE THREAD

**Issue by chipengliu** [DeftMKJ/FDAutolayout#1]
xcode 8.2, ip7plus模拟器运行就崩溃

**Comment by DeftMKJ** [comment]
已经修复了，你在试试，不行直接联系我

**Comment by chipengliu** [comment]
有个问题需要请教你一下，
我想做一个类似微博那样的tableView，但是采用autolayout的方法还是达不到想要的效果，
我tableviewcell是这样的，场地名称这一行的所有label都是上、左、右三方向对其附近的控件
price 和 地址 分别上、左、右对对齐cell
time 下、左、右对其cell
最左边的UIImageView左边对其cell，Top对其地址，bottom对其time，其他UIimageView对其第一个，间距都是15
出来的效果imageView大小会跳动，请问如果进行autolayout布局才是正确的？？

**Comment by DeftMKJ** [comment]
http://blog.csdn.net/deft_mkjing  你可以看下我的博客，里面有更详细的Demo布局，微信聊天气泡和微信朋友圈，和微博类似的
